### ISSUE TITLE
CRITICAL startup error

### ISSUE THREAD

**Issue by dimitripunch** [punchplatform/kooker#4]
Release "operator-crds" does not exist. Installing it now.
NAME: operator-crds
LAST DEPLOYED: Tue Mar  8 09:20:27 2022
NAMESPACE: punchoperator-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
Release "operator" does not exist. Installing it now.
Error: serviceaccounts "operator-controller-manager" already exists
make[1]: *** [deploy-punch] Error 1
make: *** [deploy-cots] Error 2

**Comment by dimitripunch** [comment]
Le problème semble venir de helm qui n'est pas robuste/ni idempotent. 
Un second make start regal la question. A regler d'urgence d'abord par une analyse.

**Comment by jonathanyuechun** [comment]
fixed as from https://github.com/punchplatform/punch-helm 

Root cause:

Internal problem within our publishing tooling: duplicate manifests were begin generated (service account)
